env:
  - DATABASE_URL=postgres://postgres:@localhost:5432/shchem_test
services:
  - postgresql: "9.5"
before_script:
  - psql -c 'create database shchem_test;' -U postgres
  - ./node_modules/.bin/sequelize db:migrate
