dist: trusty
language: node_js
node_js:
  - "6"
env:
  - DATABASE_URL=postgres://postgres:@localhost:5432/shchem_test
addons:
  postgresql: "9.4"
services:
  - postgresql
  - redis-server
before_script:
  - psql -c 'select version();' -U postgres
  - psql -c 'create database shchem_test;' -U postgres
  - ./node_modules/.bin/sequelize db:migrate
